
package br.com.raiadrogasil.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CalculadorDeParcelaService", targetNamespace = "http://ws.raiadrogasil.com.br/", wsdlLocation = "http://localhost:10000/calculadorDeParcela?wsdl")
public class CalculadorDeParcelaService
    extends Service
{

    private final static URL CALCULADORDEPARCELASERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:10000/calculadorDeParcela?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CALCULADORDEPARCELASERVICE_WSDL_LOCATION = url;
    }

    public CalculadorDeParcelaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadorDeParcelaService() {
        super(CALCULADORDEPARCELASERVICE_WSDL_LOCATION, new QName("http://ws.raiadrogasil.com.br/", "CalculadorDeParcelaService"));
    }

    /**
     * 
     * @return
     *     returns CalculadorDeParcela
     */
    @WebEndpoint(name = "CalculadorDeParcelaPort")
    public CalculadorDeParcela getCalculadorDeParcelaPort() {
        return (CalculadorDeParcela)super.getPort(new QName("http://ws.raiadrogasil.com.br/", "CalculadorDeParcelaPort"), CalculadorDeParcela.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculadorDeParcela
     */
    @WebEndpoint(name = "CalculadorDeParcelaPort")
    public CalculadorDeParcela getCalculadorDeParcelaPort(WebServiceFeature... features) {
        return (CalculadorDeParcela)super.getPort(new QName("http://ws.raiadrogasil.com.br/", "CalculadorDeParcelaPort"), CalculadorDeParcela.class, features);
    }

}
