
package br.com.raiadrogasil.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CalculadorDeParcela", targetNamespace = "http://ws.raiadrogasil.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculadorDeParcela {


    /**
     * 
     * @param quantidade
     * @param valorTotal
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "valorParcela", targetNamespace = "")
    @RequestWrapper(localName = "calcularParcelaSOAP", targetNamespace = "http://ws.raiadrogasil.com.br/", className = "br.com.raiadrogasil.cliente.CalcularParcelaSOAP")
    @ResponseWrapper(localName = "calcularParcelaSOAPResponse", targetNamespace = "http://ws.raiadrogasil.com.br/", className = "br.com.raiadrogasil.cliente.CalcularParcelaSOAPResponse")
    public double calcularParcelaSOAP(
        @WebParam(name = "valorTotal", targetNamespace = "")
        double valorTotal,
        @WebParam(name = "quantidade", targetNamespace = "")
        int quantidade);

}
